cluster:
  master: localhost
  node: localhost

server:
  port: 8761

spring:
  application:
    name: ipc-cloudconfig-cluster

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    hostname: ${cluster.master}
    appname: ${spring.application.name}
    app-group-name: ipc-cloudconfig
    metadata-map:
      zone: primary
      profile: ${spring.profiles.active}
      version: ${info.project.version}
  server:
    registry-sync-retry-wait-ms: 500
    a-sgcache-expiry-timeout-ms: 60000
    eviction-interval-timer-in-ms: 30000
    peer-eureka-nodes-update-interval-ms: 30000
    renewal-threshold-update-interval-ms: 15000
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${cluster.node}:8762/eureka/,http://${cluster.master}:8761/eureka/